# Generated by Django 2.1.3 on 2018-11-14 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=20)),
                ('area', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'field',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=100)),
                ('office', models.CharField(max_length=100)),
                ('phonenumber', models.CharField(max_length=50)),
                ('campus', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
