# Generated by Django 2.1.3 on 2018-11-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prosearch', '0002_auto_20181114_0806'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='area',
            field=models.CharField(max_length=1000),
        ),
    ]
